### PR TITLE
Added SWIFTLINT_REPORT and SWIFTLINT_REPORT_PATH output variables

### LINKED ISSUE #6: How can I configure output as swiftlint result as variable
I added variable for swliftlint result in shell script code.
But I can't understand how can I output to bind variable to `outputs:` in `step.yml`
Could you explain step by step to configure output?

### PR DESCRIPTION
**Pull request by lawicko**
I have added 2 output variables:

1. SWIFTLINT_REPORT - when this step is finished, this variable contains the swiftlint output. It's useful if you want to pass this output somewhere, for example to a Slack channel. This change should resolve https://github.com/kimdv/bitrise-step-swiftlint/issues/6
2. SWIFTLINT_REPORT_PATH - when this step is finished, this variable contains the path to the file that contains the report. This is useful if you organize your reports somewhere else, for example you upload them to S3 like I do. Thanks to this you can process that file further, however you want. The default file location is `$BITRISE_DEPLOY_DIR/swiftlint_report.$reporter`, so if you use `html` reporter you will end up with a `swiftlint_report.html` in the default Bitrise deploy directory.

To make this work I had to do one important change:
- I removed the `set -ex` from the source file, it's impossible to set multiple environment variables if the script exits as soon as the `swiftlint` exits. I'm not sure if this makes any difference, other than just continuing execution after `swiftlint` returns

Also, I saw that there was another merge request accepted in the meantime, which allowed for linting lines one by one. The functionality that I'm suggesting in this pull request only works in the `all` option. I think the `changed` option may be flawed, I created a bug report https://github.com/kimdv/bitrise-step-swiftlint/issues/8 and https://github.com/kimdv/bitrise-step-swiftlint/issues/9.

Finally, I tried to make sense of the test folder and test config, but it didn't make any sense to me in the current form, so I refactored it a bit so that you can now actually run `bitrise run test` and it's going to run the linting of the file in the `Test` directory using the config in the `Test/TestConfig`.

I have tested these output variables locally and on my project in bitrise.io, and it seems to work fine, I was able to make use of the `SWIFTLINT_REPORT_PATH` to upload the report to my S3 bucket. Please give it a shot and let me know what you think.

In this PR, there is everything as it was in this one: https://github.com/kimdv/bitrise-step-swiftlint/pull/10 except your unfortunate commits. I have also addressed one remaining issue with the file name, which can now be specified in the input.

### CODE REVIEW

**Comment by kimdv** [comment]
Hi again 👋

I have been working on it too! 🙈

I have merged it to master: 
https://github.com/kimdv/bitrise-step-swiftlint/commit/5576f7df61bb68a1020978fd6be8123ef4ec0a3e
https://github.com/kimdv/bitrise-step-swiftlint/commit/7b08114cc070bf75ae44e7c58ad5920ce0ed0e4d
https://github.com/kimdv/bitrise-step-swiftlint/commit/9e35975ec101f6afe162f2dc3101b5bd2ad2fa13

Please review. 🚀

It should also fix #8 and #9 
I can lint all files and diff only. Tested both. 

Please test in you workflow with 
``` yaml
- git::https://github.com/kimdv/bitrise-step-swiftlint.git@kdv/fix-lint-only-diff:
    title: Swiftlint
    inputs:
    - lint_range: changed
    - linting_path: "$BITRISE_SOURCE_DIR"
```

Sorry for the confusion and time you have used! 🙏

**Comment by lawicko** [comment]
Hey, this PR has already everything it needs, so I suggest you revert your changes and just accept and merge it. I just can't invest any more time into this for testing your code, I have already spent enough testing my implementation and I'm sure it works and it solves what is promised in the PR. I see that you are trying to make this work with the `git diff` but I'm pretty sure it's not gonna work as long as you call `swiftlint` for each file separately, but this is out of scope of this PR.

**Comment by kimdv** [comment]
Hello. 

I have tested and it works with both diff and all files. Will close this PR in favour of that. 
We need to have the same functionality for both. :) 

It works with diff as I'm appending the result on the output. 
`swiftlint_output+=$"$(swiftlint lint --path "${filename}" --reporter "${reporter}" "${flags}")"`

Again, thanks a lot for your help! 
PR: https://github.com/bitrise-io/bitrise-steplib/pull/2464

**Comment by kimdv** [comment]
Fixed in https://github.com/bitrise-io/bitrise-steplib/pull/2464#event-3303753004

**Pull request closed without merging**
